apiVersion: compute.cloud.com/v1
kind: Ec2Instance
metadata:
  name: web-server-1
  namespace: default
spec:
  instanceType: t3.medium
  amiId: ami-0c55b159cbfafe1f0  # Amazon Linux 2
  region: us-west-2
  availabilityZone: us-west-2a
  keyPair: my-keypair
  securityGroups:
    - web-security-group
  subnet: subnet-12345678
  userData: |
    #!/bin/bash
    yum update -y
    yum install -y httpd
    systemctl start httpd
    systemctl enable httpd
  tags:
    Name: k8s-managed-web-server
    ManagedBy: ec2-operator
    Environment: production
  storage:
    rootVolume:
      size: 30
      type: gp3
      encrypted: true
    additionalVolumes:
      - size: 100
        type: gp3
        deviceName: /dev/sdf
        encrypted: true
