apiVersion: compute.cloud.com/v1
kind: Ec2Instance
metadata:
  name: web-server-1
  namespace: default
spec:
  instanceType: t3.medium
  amiId: ami-09042b2f6d07d164a  # Amazon Linux 2
  region: eu-central-1
  availabilityZone: eu-central-1a
  keyPair: vmskp
  securityGroups:
    - sg-09f5c9270d3d1d5f6
  subnet: subnet-0d417570cce95f348
  userData: |
    #!/bin/bash
    yum update -y
    yum install -y httpd
    systemctl start httpd
    systemctl enable httpd
  tags:
    Name: k8s-managed-web-server
    ManagedBy: ec2-operator
    Environment: production
  storage:
    rootVolume:
      size: 30
      type: gp3
      encrypted: true
    additionalVolumes:
      - size: 100
        type: gp3
        deviceName: /dev/sdf
        encrypted: true
